// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEUYKm9xMOGk9F9XnQMPEaYeqaNtcOxZc',
    appId: '1:678774751706:web:62ba0b5083403d45e500e3',
    messagingSenderId: '678774751706',
    projectId: 'doctor-appointments-e41cd',
    authDomain: 'doctor-appointments-e41cd.firebaseapp.com',
    storageBucket: 'doctor-appointments-e41cd.appspot.com',
    measurementId: 'G-SDMYVZJXSV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBROKV1g8LhpPCPHoSZ8-8RWw9LcRrjfBU',
    appId: '1:678774751706:android:ca39b4108ba992dde500e3',
    messagingSenderId: '678774751706',
    projectId: 'doctor-appointments-e41cd',
    storageBucket: 'doctor-appointments-e41cd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjFe6pxvENKl-kvWWN6-NIyvS9kLYtRqQ',
    appId: '1:678774751706:ios:6ff719fb477634b2e500e3',
    messagingSenderId: '678774751706',
    projectId: 'doctor-appointments-e41cd',
    storageBucket: 'doctor-appointments-e41cd.appspot.com',
    iosBundleId: 'com.example.doctorAppoimentApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjFe6pxvENKl-kvWWN6-NIyvS9kLYtRqQ',
    appId: '1:678774751706:ios:ae4e8d51c025f3c3e500e3',
    messagingSenderId: '678774751706',
    projectId: 'doctor-appointments-e41cd',
    storageBucket: 'doctor-appointments-e41cd.appspot.com',
    iosBundleId: 'com.example.doctorAppoimentApp.RunnerTests',
  );
}
